services:
  db:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: storia
      MARIADB_USER: storia
      MARIADB_PASSWORD: storia
      MARIADB_ROOT_PASSWORD: storia
    ports:
      - "3306:3306"
    volumes:
      - storia_db_data:/var/lib/mysql

volumes:
  storia_db_data:
