const { withAppBuildGradle } = require("@expo/config-plugins");

/**
 * `android/` is regenerated by `expo prebuild`, so the release signing config
 * has to be re-applied on every build instead of being committed.
 *
 * This adds a `release` signingConfig that reads its keystore path/passwords
 * from Gradle project properties (STORIA_UPLOAD_*), and points
 * `buildTypes.release` at it. When those properties are absent (local
 * `assembleDebug`, the CI test job) it transparently falls back to debug
 * signing, so nothing else has to change.
 *
 * `versionCode` becomes `STORIA_VERSION_CODE` when provided (Fastlane passes the
 * CI run number) and stays at the app.json-derived value otherwise.
 *
 * Property values are supplied by fastlane/Fastfile via `gradle(properties: …)`.
 */
const RELEASE_SIGNING_CONFIG = `        release {
            if (project.hasProperty('STORIA_UPLOAD_STORE_FILE')) {
                storeFile file(STORIA_UPLOAD_STORE_FILE)
                storePassword STORIA_UPLOAD_STORE_PASSWORD
                keyAlias STORIA_UPLOAD_KEY_ALIAS
                keyPassword STORIA_UPLOAD_KEY_PASSWORD
            }
        }
`;

function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== "groovy") {
      throw new Error(
        "withAndroidReleaseSigning: expected app/build.gradle to be Groovy"
      );
    }

    let contents = config.modResults.contents;

    if (contents.includes("STORIA_UPLOAD_STORE_FILE")) {
      return config; // already applied
    }

    // 1. Add the `release` signingConfig right after the `debug { … }` block
    //    inside `signingConfigs { … }`.
    contents = contents.replace(
      /(signingConfigs\s*\{\s*\n\s*debug\s*\{[\s\S]*?\n\s*\}\n)/,
      `$1${RELEASE_SIGNING_CONFIG}`
    );

    // 2. Point buildTypes.release at signingConfigs.release when we have a
    //    keystore, else keep debug signing.
    contents = contents.replace(
      /(buildTypes\s*\{[\s\S]*?release\s*\{\s*\n(?:\s*\/\/[^\n]*\n)*)\s*signingConfig signingConfigs\.debug/,
      "$1            signingConfig project.hasProperty('STORIA_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug"
    );

    // 3. Make versionCode overridable from CI.
    contents = contents.replace(
      /versionCode \d+/,
      "versionCode project.hasProperty('STORIA_VERSION_CODE') ? project.property('STORIA_VERSION_CODE').toString().toInteger() : 1"
    );

    if (!contents.includes("signingConfigs.release")) {
      throw new Error(
        "withAndroidReleaseSigning: failed to patch buildTypes.release — the generated build.gradle shape changed"
      );
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withAndroidReleaseSigning;
